name: fieldsalescrm
description: Field Sales CRM — visit tracking, GPS check-in/out, commercial CRM and reporting for pharma/medical field teams.
publish_to: 'none'
version: 1.7.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
