import {Router} from 'express';
import {query} from '../db.js';

const router=Router();

function csvEscape(v){
  const s=String(v??'');
  return `"${s.replaceAll('"','""')}"`;
}

router.get('/performance.csv',async(req,res,next)=>{
 try{
  const period=String(req.query.period||'month');
  const trunc=['day','week','month','quarter','year'].includes(period)?period:'month';

  const r=await query(
    `SELECT e.full_name,e.state,e.hq,
            COUNT(v.id)::int total_visits,
            COUNT(v.id) FILTER(WHERE v.qualified)::int qualified_visits,
            COUNT(v.id) FILTER(WHERE NOT v.qualified)::int short_visits,
            COALESCE(SUM(o.order_value),0)::numeric order_value
     FROM employees e
     LEFT JOIN visits v ON v.employee_id=e.id AND v.check_in_at>=date_trunc($1,NOW())
     LEFT JOIN orders o ON o.employee_id=e.id AND o.order_date>=date_trunc($1,NOW())::date
     GROUP BY e.id
     ORDER BY e.state,e.hq,e.full_name`,
    [trunc]
  );

  const header=['Employee','State','HQ','Total Visits','Qualified Visits','Short Visits','Order Value'];
  const lines=[header.map(csvEscape).join(',')];
  for(const x of r.rows){
    lines.push([
      x.full_name,x.state,x.hq,x.total_visits,x.qualified_visits,x.short_visits,x.order_value
    ].map(csvEscape).join(','));
  }

  res.setHeader('Content-Type','text/csv');
  res.setHeader('Content-Disposition','attachment; filename="performance.csv"');
  res.send(lines.join('\n'));
 }catch(e){next(e);}
});

router.get('/performance.pdf',async(req,res)=>{
  res.status(501).json({
    error:'PDF rendering adapter pending deployment selection',
    note:'CSV export is implemented; PDF should be generated by the selected production rendering service.'
  });
});

export default router;
